### ISSUE TITLE
Make NN architecture diagram for our paper using this nifty tool

### ISSUE THREAD

**Issue by gianlucatruda** [gianlucatruda/Spo2_evaluation#8]
Would be awesome if we could use this: [https://alexlenail.me/NN-SVG/LeNet.html](https://alexlenail.me/NN-SVG/LeNet.html)

**Comment by Serafim179** [comment]
I'll get on that once the final architecture is established since I'm still experimenting with it.

**Comment by Serafim179** [comment]
This seems more broadly applicable: https://www.electronjs.org/apps/netron
The alexlenail seems to be less flexible with the architectures.

**Comment by gianlucatruda** [comment]
> This seems more broadly applicable: https://www.electronjs.org/apps/netron
> The alexlenail seems to be less flexible with the architectures.

Nice find!
